### ISSUE TITLE
Modifier la procédure d'installation avec le Plugin Python Manager

### ISSUE THREAD

**Issue by jp-keros** [zigbeefordomoticz/wiki#165]
https://github.com/zigbeefordomoticz/wiki/blob/master/fr-fr/Plugin_Installation.md#1---installation-du-plugin-via-python-plugin-manager-sous-linux

**Comment by pipiche38** [comment]
il faudra ajouter le sudo pip3 install ......
et également il faudra après que l'utilisateur est installé le plugin qu'il fasse la procédure git submodule ....

**Comment by jp-keros** [comment]
Presque cette procédure est plus "risquée" que de faire une installation manuelle.

Je m'occupe de tester.

**Comment by jp-keros** [comment]
Je viens de faire le test d'installation avec le Python Plugin Manager.

Le nom du plugin proposé est ZiGate : je vais leur pousser une correction.
Le dossier crée pour le plugin est Zigate. (d'où l'explication de https://easydomoticz.com/forum/viewtopic.php?p=102603#p102603 je pense)
Mais comme c'est DomoticZ qui créé le dossier et qui fait le git clone, TOUT est en root. On ne peut même pas rentrer dedans via l'explorateur de fichiers.
Un premier sudo chown -R pi:pi Zigate est nécessaire, puis on peut finir l'installation en suivant la procédure Linux. 

Par contre, le plugin à une fonction de mise à jour auto. Pas top pour nous qui avons maintenant les submodules.

Mon avis : Notre plugin est trop complexe maintenant pour être installé en 1 clic via ce Python Plugin Manager. A partir du moment où un sudo chown -R pi:pi Zigate est obligatoire, autant faire l'installation manuelle.

**Comment by pipiche38** [comment]
Si il installe tout en root et qu’ensuite les updates sont en root , pour moi c’est ok.

Le chown qu’on a ajouté c’est pour que tout appartienne à celui qui va faire l’update. Donc pas de soucis 

Envoyé de mon iPhone

**Comment by pipiche38** [comment]
Pour info: https://github.com/stas-demydiuk/domoticz-plugins-manager/pull/29
j'avais fait changer le lien

**Comment by jp-keros** [comment]
C'est quand même tordu de devoir passer en root. 

J'avais vu la modification, par contre, il me semble que le nom du plugin proposé est resté sur ZiGate.

**Comment by pipiche38** [comment]
Comme pluginmanager est un plug-in qui tourne dans DomoticZ et que sous Debian apriori il ne sait pas faire autrement, il tourne en root et donc tous fichier créé appartient à root

Pour ce qui est de Zigate c’est normal également car sinon on casse la compatibilité 

Envoyé de mon iPhone

**Comment by jp-keros** [comment]
Je pense passer cette procédure en n°2 après l'installation manuelle sous Linux car, à mon sens, elle n'est pas à privilégier.
À mettre aussi des avertissements indiquant que tous les fichiers sont en root.

**Comment by pipiche38** [comment]
j'vais essayer de bosser pour faire un PR qui puisse régler le problème des submodule. Pour ce qui est du pip install, je pense qu'il suffit de mettre ca dans la doc.

En gros le gars va installer avec PP, et ca fonctionnera pas tant qu'il n'aura pas fait les pip install

**Comment by jp-keros** [comment]
Tu penses que ça vaut le coup de passer du temps dessus ? 

- le nom du dossier n'est pas le bon (ça peut certainement être réglé)
- les fichiers seront en root : ça fonctionnera tant que la personne n'aura jamais besoin de mettre le nez dans le dossier du plugin
- Il faudra quand même faire les pip install

Ce python plugin manager est très bien pour des plugins simples, mais on est passé un cran au-dessus : autant faire l'installation manuelle sous Linux.

**Comment by pipiche38** [comment]
je pense qu'il y a des utilisateurs, et je ne suis pas certain qu'il faille beaucoup de temps pour modifier.
Par contre j'ai pas mal de boulot en ce moment, donc moins de liberté
