### ISSUE TITLE
Channel 25

### ISSUE THREAD

**Issue by jetmcquack** [zigbeefordomoticz/wiki#280]
Hello, unfortunately I’m using channel 25 for my zigbee network, and i can’t change it. Is it possible to pair Legrand Remote switch 067774 even if I’m not on channel 11?

**Comment by pipiche38** [comment]
Your first place to get support is via the Forums.

    English channel : https://www.domoticz.com/forum/viewforum.php?f=68
    French Channel : https://easydomoticz.com/forum/viewforum.php?f=28&sid=a8633a9d8cb2acccb32872543b50fd47
